# Generated by Django 4.1.7 on 2023-05-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0003_books_image_remove_books_author_books_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('pages_count', models.IntegerField(default=1, verbose_name='Количество страниц')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Количество скачиваний')),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
                ('image', models.ImageField(default='default_image.png', upload_to='images/')),
                ('author', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='librarySite.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
