# Generated by Django 4.2 on 2023-05-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0005_remove_author_first_name_remove_author_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
