# Generated by Django 4.2 on 2023-05-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0006_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
    ]
