# Generated by Django 4.2 on 2023-05-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0007_remove_author_birth_date_remove_author_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
