# Generated by Django 4.1.7 on 2023-05-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0009_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
