# Generated by Django 4.1.7 on 2023-05-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0010_remove_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
