# Generated by Django 4.2 on 2023-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0011_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='loremka.pdf', null=True, upload_to='book_files/', verbose_name='Файл книги'),
        ),
    ]
