# Generated by Django 4.1.7 on 2023-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0016_book_user_favorites_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_favorites',
        ),
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='book',
            name='user_favorites',
        ),
        migrations.AddField(
            model_name='book',
            name='user_favorites',
            field=models.ManyToManyField(related_name='favorites_books', to='librarySite.profile', verbose_name='В избранном'),
        ),
    ]
