# Generated by Django 4.1.7 on 2023-05-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0017_remove_book_in_favorites_book_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='librarySite.book'),
        ),
    ]
