# Generated by Django 4.1.7 on 2023-05-10 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarySite', '0018_alter_like_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата события')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(default='images/default_image.png', upload_to='images/news/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/default_image.png', upload_to='images/books/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_favorites',
            field=models.ManyToManyField(related_name='favorite_books', to='librarySite.profile', verbose_name='В избранном'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
