# Generated by Django 4.1.7 on 2023-05-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySite', '0020_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='images/news/default_image.png', upload_to='images/news/', verbose_name='Изображение'),
        ),
    ]
